# Generates include/version.h from the release version.
# Priority: $env:SBPP_VERSION (CI sets it from the tag) -> git describe (local dev) -> fallback.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot   # tools\ -> repo root

$ver = $env:SBPP_VERSION
if (-not $ver) {
    $desc = & git -C $root describe --tags --always --dirty 2>$null
    if ($LASTEXITCODE -eq 0 -and $desc) {
        if ($desc -match '-\d+-g[0-9a-fA-F]+') {
            # Commits exist after the latest tag -> dev build off that tag's MAJOR.MINOR.PATCH.
            $base = ($desc -replace '-\d+-g[0-9a-fA-F]+.*$', '') -replace '^v', ''
            if ($base -match '^(\d+)\.(\d+)\.(\d+)') {
                $ver = "$($Matches[1]).$($Matches[2]).$($Matches[3])-dev"
            }
        } else {
            $ver = $desc   # HEAD is exactly on a tag
        }
    }
}
if (-not $ver) { $ver = '0.0.0-dev' }
$ver = $ver -replace '^v', ''

if ($ver -match '^(\d+)\.(\d+)\.(\d+)(?:-(.+))?$') {
    $maj = [int]$Matches[1]; $min = [int]$Matches[2]; $pat = [int]$Matches[3]; $pre = $Matches[4]
} else {
    $maj = 0; $min = 0; $pat = 0; $pre = 'dev'
}
$full = if ($pre) { "$maj.$min.$pat-$pre" } else { "$maj.$min.$pat" }

$lines = @(
    '#pragma once',
    '// AUTO-GENERATED by tools/gen-version.ps1 at build time. Do not edit; not committed.',
    "#define SBPP_VER_MAJOR $maj",
    "#define SBPP_VER_MINOR $min",
    "#define SBPP_VER_PATCH $pat",
    '#define SBPP_VER_BUILD 0',
    "#define SBPP_VERSION_STR    L`"$full`"",
    "#define SBPP_VERSION_NARROW `"$full`""
)
$out = Join-Path (Join-Path $root 'include') 'version.h'
Set-Content -Path $out -Value $lines -Encoding ASCII
Write-Host "gen-version: $full -> $out"
